//
//  AdminScript_GenerateCodes.swift
//  FitHub
//
//  Admin script to generate and add influencer codes to Firestore
//  Run this from a script or admin dashboard
//

import Foundation
import FirebaseFirestore
import FirebaseAuth
import Combine

/// Admin utility to create referral codes in Firestore
/// ObservableObject for use in SwiftUI views
final class ReferralCodeAdmin: ObservableObject {
    private let db = Firestore.firestore()
    
    /// Creates a new referral code for an influencer
    /// - Parameters:
    ///   - code: The referral code (will be uppercased)
    ///   - influencerName: Name of the influencer
    ///   - influencerEmail: Optional email for the influencer
    ///   - notes: Optional notes about this influencer
    func createReferralCode(
        code: String,
        influencerName: String,
        influencerEmail: String? = nil,
        notes: String? = nil
    ) async throws {
        let uppercasedCode = code.uppercased()
        
        // Validate code
        guard ReferralCodeGenerator.isValidCode(uppercasedCode) else {
            throw NSError(
                domain: "ReferralCodeAdmin",
                code: -1,
                userInfo: [NSLocalizedDescriptionKey: "Invalid code format: \(code)"]
            )
        }
        
        let codeRef = db.collection("referralCodes").document(uppercasedCode)
        
        // Check if code already exists
        let existingDoc = try await codeRef.getDocument()
        if existingDoc.exists {
            throw NSError(
                domain: "ReferralCodeAdmin",
                code: -2,
                userInfo: [NSLocalizedDescriptionKey: "Code already exists: \(uppercasedCode)"]
            )
        }
        
        // Get current user ID if authenticated
        let userId = Auth.auth().currentUser?.uid ?? "self_service"
        
        // Create the code document
        try await codeRef.setData([
            "code": uppercasedCode,
            "influencerName": influencerName,
            "influencerEmail": influencerEmail ?? "",
            "notes": notes ?? "",
            "isActive": true,
            "createdAt": FieldValue.serverTimestamp(),
            "createdBy": userId, // Track who created it
            "usageCount": 0,
            "usedBy": []
        ])
        
        print("✅ Created referral code: \(uppercasedCode) for \(influencerName)")
    }
    
    /// Generates and creates a new referral code automatically
    /// Automatically adds random numbers to make code unique if it already exists
    /// Throws error if email is already associated with another referral code
    func createAutoGeneratedCode(
        influencerName: String,
        influencerEmail: String? = nil,
        notes: String? = nil
    ) async throws -> String {
        // Check if email is already used BEFORE attempting to generate code
        if let email = influencerEmail, !email.isEmpty {
            let emailUsed = try await checkEmailExists(email)
            if emailUsed {
                throw NSError(
                    domain: "ReferralCodeAdmin",
                    code: -4,
                    userInfo: [NSLocalizedDescriptionKey: "Email is already registered with another referral code"]
                )
            }
        }
        
        var attempts = 0
        let maxAttempts = 20
        
        // Generate base code from name
        let baseCode = ReferralCodeGenerator.generateCodeFromName(influencerName)
        
        while attempts < maxAttempts {
            var code: String
            if attempts == 0 {
                // First attempt: use base code
                code = baseCode
            } else {
                // Retry: append random number to base code
                let randomNum = Int.random(in: 1...9999)
                // Ensure total length doesn't exceed 10 characters
                let maxBaseLength = max(4, 10 - String(randomNum).count)
                let trimmedBase = String(baseCode.prefix(maxBaseLength))
                code = trimmedBase + String(randomNum)
            }
            
            do {
                try await createReferralCode(
                    code: code,
                    influencerName: influencerName,
                    influencerEmail: influencerEmail,
                    notes: notes
                )
                return code
            } catch {
                // If code exists, try again with different random number
                if let nsError = error as NSError?, nsError.code == -2 {
                    if attempts < maxAttempts - 1 {
                        attempts += 1
                        continue
                    }
                }
                // Other errors, throw immediately
                throw error
            }
        }
        
        throw NSError(
            domain: "ReferralCodeAdmin",
            code: -3,
            userInfo: [NSLocalizedDescriptionKey: "Failed to generate unique code after \(maxAttempts) attempts"]
        )
    }
    
    /// Deactivates a referral code
    func deactivateCode(_ code: String) async throws {
        let codeRef = db.collection("referralCodes").document(code.uppercased())
        try await codeRef.updateData(["isActive": false])
        print("✅ Deactivated referral code: \(code.uppercased())")
    }
    
    /// Gets statistics for a referral code
    func getCodeStats(_ code: String) async throws -> [String: Any]? {
        let codeRef = db.collection("referralCodes").document(code.uppercased())
        let doc = try await codeRef.getDocument()
        return doc.data()
    }
    
    /// Lists all referral codes
    func listAllCodes() async throws -> [[String: Any]] {
        let snapshot = try await db.collection("referralCodes").getDocuments()
        return snapshot.documents.map { doc in
            var data = doc.data()
            data["id"] = doc.documentID
            return data
        }
    }
    
    /// Checks if an email is already used by another referral code
    func checkEmailExists(_ email: String) async throws -> Bool {
        guard !email.isEmpty else { return false }
        
        let snapshot = try await db.collection("referralCodes")
            .whereField("influencerEmail", isEqualTo: email)
            .limit(to: 1)
            .getDocuments()
        
        return !snapshot.documents.isEmpty
    }
}

// MARK: - Example Usage
/*
let admin = ReferralCodeAdmin()

// Create a code manually
try await admin.createReferralCode(
    code: "ANTHONY",
    influencerName: "Anthony Cantu",
    influencerEmail: "anthony@example.com",
    notes: "Main influencer"
)

// Auto-generate a code
let code = try await admin.createAutoGeneratedCode(
    influencerName: "John Doe",
    influencerEmail: "john@example.com"
)

// Get stats
let stats = try await admin.getCodeStats("ANTHONY")
print("Usage count: \(stats?["usageCount"] ?? 0)")

// List all codes
let allCodes = try await admin.listAllCodes()
*/

