//
//  AdminScript_GenerateCodes.swift
//  FitHub
//
//  Admin script to generate and add influencer codes to Firestore
//  Run this from a script or admin dashboard
//

import Foundation
import FirebaseFirestore
import Combine

/// Admin utility to create referral codes in Firestore
/// ObservableObject for use in SwiftUI views
final class ReferralCodeAdmin: ObservableObject {
    private let db = Firestore.firestore()

    /// Creates a new referral code for an influencer
    /// - Parameters:
    ///   - code: The referral code (will be uppercased)
    ///   - influencerName: Name of the influencer
    ///   - influencerEmail: Optional email for the influencer
    ///   - notes: Optional notes about this influencer
    func createReferralCode(
        code: String,
        influencerName: String,
        influencerEmail: String? = nil,
        acceptedTermsVersion: String
    ) async throws {
        // Check if user already has a referral code
        if let existingCode = try await ReferralRetriever.getCreatedCode(), !existingCode.isEmpty {
            throw ReferralError.uidHasCodeAlready
        }

        let uppercasedCode = code.uppercased()

        // Validate code
        guard ReferralCodeGenerator.isValidCode(uppercasedCode) else {
            throw ReferralError.invalidCodeFormat
        }

        let codeRef = db.collection("referralCodes").document(uppercasedCode)

        // Check if code already exists
        let existingDoc = try await codeRef.getDocument()
        if existingDoc.exists {
            throw ReferralError.codeAlreadyTaken
        }

        // Get current user ID if authenticated
        guard let userId = AuthService.getUid() else { return }

        // Create the code document
        try await codeRef.setData([
            "code": uppercasedCode,
            "influencerName": influencerName,
            "influencerEmail": influencerEmail ?? "",
            "isActive": true,
            "createdAt": FieldValue.serverTimestamp(),
            "createdBy": userId,
            "usageCount": 0,
            "usedBy": [],
            "acceptedTermsVersion": acceptedTermsVersion,
            "termsAcceptedAt": FieldValue.serverTimestamp()
        ])

        print("✅ Created referral code: \(uppercasedCode) for \(influencerName)")
    }

    /// Generates and creates a new referral code automatically
    /// Automatically adds random numbers to make code unique if it already exists
    /// Throws error if email is already associated with another referral code
    func createAutoGeneratedCode(
        influencerName: String,
        influencerEmail: String? = nil,
        acceptedTermsVersion: String
    ) async throws -> String {
        // Check if user already has a referral code
        if let existingCode = try await ReferralRetriever.getCreatedCode(), !existingCode.isEmpty {
            throw ReferralError.uidHasCodeAlready
        }

        // Check if email is already used BEFORE attempting to generate code
        if let email = influencerEmail, !email.isEmpty {
            let emailUsed = try await checkEmailExists(email)
            if emailUsed {
                throw ReferralError.emailHasCodeAlready
            }
        }

        var attempts = 0
        let maxAttempts = 20

        // Generate base code from name
        let baseCode = ReferralCodeGenerator.generateCodeFromName(influencerName)

        while attempts < maxAttempts {
            var code: String
            if attempts == 0 {
                // First attempt: use base code
                code = baseCode
            } else {
                // Retry: append random number to base code
                let randomNum = Int.random(in: 1...9999)
                // Ensure total length doesn't exceed 10 characters
                let maxBaseLength = max(4, 10 - String(randomNum).count)
                let trimmedBase = String(baseCode.prefix(maxBaseLength))
                code = trimmedBase + String(randomNum)
            }

            do {
                try await createReferralCode(
                    code: code,
                    influencerName: influencerName,
                    influencerEmail: influencerEmail,
                    acceptedTermsVersion: acceptedTermsVersion
                )
                return code
            } catch {
                // If code exists, try again with different random number
                if case ReferralError.codeAlreadyTaken = error {
                    if attempts < maxAttempts - 1 {
                        attempts += 1
                        continue
                    }
                }
                // Other errors, throw immediately
                throw error
            }
        }

        throw ReferralError.unableToGenerateUniqueCode
    }

    /// Deactivates a referral code
    func deactivateCode(_ code: String) async throws {
        let codeRef = db.collection("referralCodes").document(code.uppercased())
        try await codeRef.updateData(["isActive": false])
        print("✅ Deactivated referral code: \(code.uppercased())")
    }

    private func getCodeData(_ code: String) async throws -> [String: Any] {
        let codeRef = db.collection("referralCodes").document(code.uppercased())

        do {
            let doc = try await codeRef.getDocument()
            guard doc.exists else { throw ReferralAdminError.codeNotFound } // Document does NOT exist → logical "not found"
            guard let data = doc.data() else { throw ReferralAdminError.malformedDocument } // Exists but no data → bad document
            return data
        } catch {
            let nsError = error as NSError
            if nsError.domain == FirestoreErrorDomain,
               nsError.code == FirestoreErrorCode.Code.unavailable.rawValue {
                throw ReferralAdminError.databaseUnavailable
            }
            throw error
        }
    }

    func getData(_ code: String) async throws -> (code: String, email: String, notes: String, stats: CodeStats, stripe: StripeAffiliateStatus, acceptedTermsVersion: String?) {
        let codeData = try await getCodeData(code)

        let affiliate = loadAffiliateInfo(from: codeData)
        let stats     = loadReferralInfo(from: codeData)
        let stripe    = loadStripeStatus(from: codeData)
        let acceptedTermsVersion = codeData["acceptedTermsVersion"] as? String

        return (
            code: affiliate.code,
            email: affiliate.email,
            notes: affiliate.notes,
            stats: stats,
            stripe: stripe,
            acceptedTermsVersion: acceptedTermsVersion
        )
    }

    func updateAcceptedTerms(code: String, version: String) async throws {
        guard let userId = AuthService.getUid() else {
            throw NSError(domain: "ReferralCodeAdmin", code: -1, userInfo: [NSLocalizedDescriptionKey: "User not authenticated"])
        }

        let codeRef = db.collection("referralCodes").document(code.uppercased())
        let codeDoc = try await codeRef.getDocument()

        guard codeDoc.exists,
              let codeData = codeDoc.data(),
              let createdBy = codeData["createdBy"] as? String,
              createdBy == userId else {
            throw ReferralAdminError.codeNotFound
        }

        try await codeRef.updateData([
            "acceptedTermsVersion": version,
            "termsAcceptedAt": FieldValue.serverTimestamp()
        ])
    }

    private func loadAffiliateInfo(from codeData: [String: Any]) -> (code: String, email: String, notes: String) {
        let code    = codeData["code"] as? String ?? ""
        let email   = codeData["influencerEmail"] as? String ?? ""
        let notes   = codeData["notes"] as? String ?? ""

        return (code, email, notes)
    }

    private func loadReferralInfo(from codeData: [String: Any]) -> CodeStats {
        let usedBy             = (codeData["usedBy"] as? [String] ?? []).filter { !$0.isEmpty }
        let monthlyPurchasedBy = (codeData["monthlyPurchasedBy"] as? [String] ?? []).filter { !$0.isEmpty }
        let annualPurchasedBy  = (codeData["annualPurchasedBy"] as? [String] ?? []).filter { !$0.isEmpty }
        let lifetimePurchasedBy = (codeData["lifetimePurchasedBy"] as? [String] ?? []).filter { !$0.isEmpty }

        return CodeStats(
            signUps: usedBy.count,
            monthlyPurchases: monthlyPurchasedBy.count,
            annualPurchases: annualPurchasedBy.count,
            lifetimePurchases: lifetimePurchasedBy.count,
            lastUsedAt: (codeData["lastUsedAt"] as? Timestamp)?.dateValue(),
            lastPurchaseAt: (codeData["lastPurchaseAt"] as? Timestamp)?.dateValue()
        )
    }

    private func loadStripeStatus(from codeData: [String: Any]) -> StripeAffiliateStatus {
        let accountId         = codeData["stripeAccountId"] as? String
        let detailsSubmitted  = codeData["stripeDetailsSubmitted"] as? Bool ?? false
        let payoutsEnabled    = codeData["stripePayoutsEnabled"] as? Bool ?? false
        let requirementsDue   = codeData["stripeRequirementsDue"] as? [String] ?? []
        let lastStripeSyncAt  = (codeData["stripeLastStripeSyncAt"] as? Timestamp)?.dateValue()
        let lastOnboardingAt  = (codeData["stripeLastOnboardingAt"] as? Timestamp)?.dateValue()
        let lastDashboardLinkAt = (codeData["stripeLastDashboardLinkAt"] as? Timestamp)?.dateValue()

        return StripeAffiliateStatus(
            accountId: accountId,
            detailsSubmitted: detailsSubmitted,
            payoutsEnabled: payoutsEnabled,
            requirementsDue: requirementsDue,
            lastStripeSyncAt: lastStripeSyncAt,
            lastOnboardingAt: lastOnboardingAt,
            lastDashboardLinkAt: lastDashboardLinkAt
        )
    }

    /// Checks if an email is already used by another referral code
    func checkEmailExists(_ email: String) async throws -> Bool {
        guard !email.isEmpty else { return false }

        let snapshot = try await db.collection("referralCodes")
            .whereField("influencerEmail", isEqualTo: email)
            .limit(to: 1)
            .getDocuments()

        return !snapshot.documents.isEmpty
    }

    /// Updates the email address for a referral code
    func updateCreatedReferralCodeEmail(code: String, newEmail: String) async throws {
        guard let userId = AuthService.getUid() else {
            throw NSError(
                domain: "ReferralCodeAdmin",
                code: -5,
                userInfo: [NSLocalizedDescriptionKey: "User not authenticated"]
            )
        }

        let codeRef = db.collection("referralCodes").document(code.uppercased())
        let codeDoc = try await codeRef.getDocument()

        guard codeDoc.exists else {
            throw NSError(
                domain: "ReferralCodeAdmin",
                code: -2,
                userInfo: [NSLocalizedDescriptionKey: "Referral code not found"]
            )
        }

        // Verify the code was created by the current user
        if let createdBy = codeDoc.data()?["createdBy"] as? String,
           createdBy != userId {
            throw NSError(
                domain: "ReferralCodeAdmin",
                code: -6,
                userInfo: [NSLocalizedDescriptionKey: "You can only update your own referral code"]
            )
        }

        // Check if new email is already used by another code
        if !newEmail.isEmpty {
            let emailUsed = try await checkEmailExists(newEmail)
            if emailUsed {
                // Check if it's the same code
                let existingCodeSnapshot = try await db.collection("referralCodes")
                    .whereField("influencerEmail", isEqualTo: newEmail)
                    .limit(to: 1)
                    .getDocuments()

                if let existingCodeId = existingCodeSnapshot.documents.first?.documentID,
                   existingCodeId.uppercased() != code.uppercased() {
                    throw ReferralError.emailHasCodeAlready
                }
            }
        }

        // Update the email
        try await codeRef.updateData([
            "influencerEmail": newEmail
        ])

        print("✅ Updated email for referral code: \(code.uppercased())")
    }
}

// MARK: - Example Usage
/*
let admin = ReferralCodeAdmin()

// Create a code manually
try await admin.createReferralCode(
    code: "ANTHONY",
    influencerName: "Anthony Cantu",
    influencerEmail: "anthony@example.com",
    notes: "Main influencer"
)

// Auto-generate a code
let code = try await admin.createAutoGeneratedCode(
    influencerName: "John Doe",
    influencerEmail: "john@example.com"
)

// Get stats
let stats = try await admin.getCodeStats("ANTHONY")
print("Usage count: \(stats?["usageCount"] ?? 0)")

// List all codes
let allCodes = try await admin.listAllCodes()
*/
