//
//  AdminScript_GenerateCodes.swift
//  FitHub
//
//  Admin script to generate and add influencer codes to Firestore
//  Run this from a script or admin dashboard
//

import Foundation
import FirebaseFirestore
import Combine

/// Admin utility to create referral codes in Firestore
/// ObservableObject for use in SwiftUI views
final class ReferralCodeAdmin: ObservableObject {
    private let db = Firestore.firestore()
    
    /// Creates a new referral code for an influencer
    /// - Parameters:
    ///   - code: The referral code (will be uppercased)
    ///   - influencerName: Name of the influencer
    ///   - influencerEmail: Optional email for the influencer
    ///   - notes: Optional notes about this influencer
    func createReferralCode(
        code: String,
        influencerName: String,
        influencerEmail: String? = nil,
        notes: String? = nil,
        payoutMethod: String? = nil
    ) async throws {
        // Check if user already has a referral code
        if let existingCode = try await ReferralRetriever.getCreatedCode(), !existingCode.isEmpty {
            throw ReferralError.uidHasCodeAlready
        }
        
        let uppercasedCode = code.uppercased()
        
        // Validate code
        guard ReferralCodeGenerator.isValidCode(uppercasedCode) else {
            throw ReferralError.invalidCodeFormat
        }
        
        let codeRef = db.collection("referralCodes").document(uppercasedCode)
        
        // Check if code already exists
        let existingDoc = try await codeRef.getDocument()
        if existingDoc.exists {
            throw ReferralError.codeAlreadyTaken
        }
        
        // Get current user ID if authenticated
        guard let userId = AuthService.getUid() else { return }
        
        // Create the code document
        try await codeRef.setData([
            "code": uppercasedCode,
            "influencerName": influencerName,
            "influencerEmail": influencerEmail ?? "",
            "notes": notes ?? "",
            "payoutMethod": payoutMethod ?? "",
            "isActive": true,
            "createdAt": FieldValue.serverTimestamp(),
            "createdBy": userId, // Track who created it
            "usageCount": 0,
            "usedBy": []
        ])
        
        print("✅ Created referral code: \(uppercasedCode) for \(influencerName)")
    }
    
    /// Generates and creates a new referral code automatically
    /// Automatically adds random numbers to make code unique if it already exists
    /// Throws error if email is already associated with another referral code
    func createAutoGeneratedCode(
        influencerName: String,
        influencerEmail: String? = nil,
        notes: String? = nil,
        payoutMethod: String? = nil
    ) async throws -> String {
        // Check if user already has a referral code
        if let existingCode = try await ReferralRetriever.getCreatedCode(), !existingCode.isEmpty {
            throw ReferralError.uidHasCodeAlready
        }
        
        // Check if email is already used BEFORE attempting to generate code
        if let email = influencerEmail, !email.isEmpty {
            let emailUsed = try await checkEmailExists(email)
            if emailUsed {
                throw ReferralError.emailHasCodeAlready
            }
        }
        
        var attempts = 0
        let maxAttempts = 20
        
        // Generate base code from name
        let baseCode = ReferralCodeGenerator.generateCodeFromName(influencerName)
        
        while attempts < maxAttempts {
            var code: String
            if attempts == 0 {
                // First attempt: use base code
                code = baseCode
            } else {
                // Retry: append random number to base code
                let randomNum = Int.random(in: 1...9999)
                // Ensure total length doesn't exceed 10 characters
                let maxBaseLength = max(4, 10 - String(randomNum).count)
                let trimmedBase = String(baseCode.prefix(maxBaseLength))
                code = trimmedBase + String(randomNum)
            }
            
            do {
                try await createReferralCode(
                    code: code,
                    influencerName: influencerName,
                    influencerEmail: influencerEmail,
                    notes: notes,
                    payoutMethod: payoutMethod
                )
                return code
            } catch {
                // If code exists, try again with different random number
                if case ReferralError.codeAlreadyTaken = error {
                    if attempts < maxAttempts - 1 {
                        attempts += 1
                        continue
                    }
                }
                // Other errors, throw immediately
                throw error
            }
        }
        
        throw ReferralError.unableToGenerateUniqueCode
    }
    
    /// Deactivates a referral code
    func deactivateCode(_ code: String) async throws {
        let codeRef = db.collection("referralCodes").document(code.uppercased())
        try await codeRef.updateData(["isActive": false])
        print("✅ Deactivated referral code: \(code.uppercased())")
    }
    
    /// Gets statistics for a referral code
    func getCodeData(_ code: String) async throws -> [String: Any]? {
        let codeRef = db.collection("referralCodes").document(code.uppercased())
        let doc = try await codeRef.getDocument()
        return doc.data()
    }
    
    func getData(_ code: String) async throws -> (code: String, email: String, pMethod: String, notes: String, stats: CodeStats, stripe: StripeAffiliateStatus) {
        let codeData = try await getCodeData(code)
        let (code, email, pMethod, notes) = loadAffiliateInfo(from: codeData)
        let stats    = try await loadReferralInfo(codeData: codeData)
        let stripe   = loadStripeStatus(from: codeData)
        return (code, email, pMethod, notes, stats, stripe)
    }
    
    private func loadAffiliateInfo(from codeData: [String: Any]?) -> (code: String, email: String, pMethod: String, notes: String) {
        guard let data = codeData else { return ("", "", "", "") }

        let code    = data["code"] as? String ?? ""
        let email   = data["influencerEmail"] as? String ?? ""
        let pMethod = data["payoutMethod"] as? String ?? ""
        let notes   = data["notes"] as? String ?? ""

        return (code, email, pMethod, notes)
    }

    private func loadStripeStatus(from codeData: [String: Any]?) -> StripeAffiliateStatus {
        guard let data = codeData else { return .empty }

        let accountId = data["stripeAccountId"] as? String
        let detailsSubmitted = data["stripeDetailsSubmitted"] as? Bool ?? false
        let payoutsEnabled = data["stripePayoutsEnabled"] as? Bool ?? false
        let requirementsDue = data["stripeRequirementsDue"] as? [String] ?? []
        let lastStripeSyncAt = (data["stripeLastStripeSyncAt"] as? Timestamp)?.dateValue()
        let lastOnboardingAt = (data["stripeLastOnboardingAt"] as? Timestamp)?.dateValue()
        let lastDashboardLinkAt = (data["stripeLastDashboardLinkAt"] as? Timestamp)?.dateValue()

        return StripeAffiliateStatus(
            accountId: accountId,
            detailsSubmitted: detailsSubmitted,
            payoutsEnabled: payoutsEnabled,
            requirementsDue: requirementsDue,
            lastStripeSyncAt: lastStripeSyncAt,
            lastOnboardingAt: lastOnboardingAt,
            lastDashboardLinkAt: lastDashboardLinkAt
        )
    }

    func loadReferralInfo(codeData: [String: Any]?) async throws -> CodeStats {
        guard let data = codeData else { return CodeStats.blankStats }
        // parse arrays, ignoring empty strings
        let usedBy = (data["usedBy"] as? [String] ?? []).filter { !$0.isEmpty }
        let monthlyPurchasedBy = (data["monthlyPurchasedBy"] as? [String] ?? []).filter { !$0.isEmpty }
        let annualPurchasedBy = (data["annualPurchasedBy"] as? [String] ?? []).filter { !$0.isEmpty }
        let lifetimePurchasedBy = (data["lifetimePurchasedBy"] as? [String] ?? []).filter { !$0.isEmpty }
        
        return CodeStats(
            signUps: usedBy.count,
            monthlyPurchases: monthlyPurchasedBy.count,
            annualPurchases: annualPurchasedBy.count,
            lifetimePurchases: lifetimePurchasedBy.count,
            lastUsedAt: (data["lastUsedAt"] as? Timestamp)?.dateValue(),
            lastPurchaseAt: (data["lastPurchaseAt"] as? Timestamp)?.dateValue()
        )
    }
    
    /// Lists all referral codes
    func listAllCodes() async throws -> [[String: Any]] {
        let snapshot = try await db.collection("referralCodes").getDocuments()
        return snapshot.documents.map { doc in
            var data = doc.data()
            data["id"] = doc.documentID
            return data
        }
    }
    
    /// Checks if an email is already used by another referral code
    func checkEmailExists(_ email: String) async throws -> Bool {
        guard !email.isEmpty else { return false }
        
        let snapshot = try await db.collection("referralCodes")
            .whereField("influencerEmail", isEqualTo: email)
            .limit(to: 1)
            .getDocuments()
        
        return !snapshot.documents.isEmpty
    }
    
    /// Updates the email address for a referral code
    func updateCreatedReferralCodeEmail(code: String, newEmail: String) async throws {
        guard let userId = AuthService.getUid() else {
            throw NSError(
                domain: "ReferralCodeAdmin",
                code: -5,
                userInfo: [NSLocalizedDescriptionKey: "User not authenticated"]
            )
        }
        
        let codeRef = db.collection("referralCodes").document(code.uppercased())
        let codeDoc = try await codeRef.getDocument()
        
        guard codeDoc.exists else {
            throw NSError(
                domain: "ReferralCodeAdmin",
                code: -2,
                userInfo: [NSLocalizedDescriptionKey: "Referral code not found"]
            )
        }
        
        // Verify the code was created by the current user
        if let createdBy = codeDoc.data()?["createdBy"] as? String,
           createdBy != userId {
            throw NSError(
                domain: "ReferralCodeAdmin",
                code: -6,
                userInfo: [NSLocalizedDescriptionKey: "You can only update your own referral code"]
            )
        }
        
        // Check if new email is already used by another code
        if !newEmail.isEmpty {
            let emailUsed = try await checkEmailExists(newEmail)
            if emailUsed {
                // Check if it's the same code
                let existingCodeSnapshot = try await db.collection("referralCodes")
                    .whereField("influencerEmail", isEqualTo: newEmail)
                    .limit(to: 1)
                    .getDocuments()
                
                if let existingCodeId = existingCodeSnapshot.documents.first?.documentID,
                   existingCodeId.uppercased() != code.uppercased() {
                    throw ReferralError.emailHasCodeAlready
                }
            }
        }
        
        // Update the email
        try await codeRef.updateData([
            "influencerEmail": newEmail
        ])
        
        print("✅ Updated email for referral code: \(code.uppercased())")
    }
}

// MARK: - Example Usage
/*
let admin = ReferralCodeAdmin()

// Create a code manually
try await admin.createReferralCode(
    code: "ANTHONY",
    influencerName: "Anthony Cantu",
    influencerEmail: "anthony@example.com",
    notes: "Main influencer"
)

// Auto-generate a code
let code = try await admin.createAutoGeneratedCode(
    influencerName: "John Doe",
    influencerEmail: "john@example.com"
)

// Get stats
let stats = try await admin.getCodeStats("ANTHONY")
print("Usage count: \(stats?["usageCount"] ?? 0)")

// List all codes
let allCodes = try await admin.listAllCodes()
*/

