//
//  ADD_CODES_EXAMPLE.swift
//  FitHub
//
//  Example script to add referral codes programmatically
//  You can add this to your app temporarily, or create a separate admin tool
//

import Foundation
import FirebaseFirestore

// MARK: - Simple Usage Example

/// Quick function to add multiple referral codes at once
func addReferralCodes() async {
    let admin = ReferralCodeAdmin()
    
    // Example: Add codes for your influencers
    let influencers = [
        ("ANTHONY", "Anthony Cantu", "anthony@example.com", "Main influencer"),
        ("JOHN", "John Doe", "john@example.com", "Fitness influencer"),
        ("SARAH", "Sarah Smith", "sarah@example.com", "Yoga influencer"),
        // Add more here...
    ]
    
    for (code, name, email, notes) in influencers {
        do {
            try await admin.createReferralCode(
                code: code,
                influencerName: name,
                influencerEmail: email,
                notes: notes
            )
        } catch {
            print("❌ Failed to create code \(code): \(error.localizedDescription)")
        }
    }
    
    print("✅ Finished adding referral codes")
}

// MARK: - Auto-generate codes from names

/// Auto-generate codes from influencer names
func addAutoGeneratedCodes() async {
    let admin = ReferralCodeAdmin()
    
    let influencers = [
        ("Anthony Cantu", "anthony@example.com", "Main influencer"),
        ("John Doe", "john@example.com", "Fitness influencer"),
        ("Sarah Smith", "sarah@example.com", "Yoga influencer"),
        // Add more here...
    ]
    
    for (name, email, notes) in influencers {
        do {
            let code = try await admin.createAutoGeneratedCode(
                influencerName: name,
                influencerEmail: email,
                notes: notes
            )
            print("✅ Generated code: \(code) for \(name)")
        } catch {
            print("❌ Failed to create code for \(name): \(error.localizedDescription)")
        }
    }
}

// MARK: - How to Use
/*
 Option 1: Add to your app temporarily
 - Add this file to your Xcode project
 - Call from somewhere in your app (e.g., a debug menu or one-time setup)
 
 Option 2: Create a simple admin view in your app
 - Add a SwiftUI view with a form
 - Let yourself input influencer details
 - Call admin.createReferralCode() when you submit
 
 Option 3: Create a standalone script
 - Create a simple command-line tool
 - Run it when you need to add codes
 
 Example usage:
 Task {
     await addReferralCodes()
 }
 */

