//
//  AddReferralCodes.swift
//  FitHub
//
//  One-time script to add referral codes programmatically
//  Run this once to set up all your influencer codes
//

import Foundation
import FirebaseFirestore
import FirebaseCore

// MARK: - Configuration
// Edit this list with your influencers:

let influencers: [(name: String, email: String?, notes: String?)] = [
    ("Anthony Cantu", "anthony@example.com", "Main influencer"),
    ("John Doe", "john@example.com", "Fitness influencer"),
    ("Sarah Smith", "sarah@example.com", "Yoga influencer"),
    // Add more influencers here...
]

// MARK: - Main Function

@MainActor
func addAllReferralCodes() async {
    // Make sure Firebase is initialized
    if FirebaseApp.app() == nil {
        FirebaseApp.configure()
    }
    
    let admin = ReferralCodeAdmin()
    
    print("🚀 Starting to add referral codes...\n")
    
    for (name, email, notes) in influencers {
        do {
            // Auto-generate code from name
            let code = try await admin.createAutoGeneratedCode(
                influencerName: name,
                influencerEmail: email,
                notes: notes
            )
            print("✅ Created: \(code) for \(name)")
        } catch {
            print("❌ Failed to create code for \(name): \(error.localizedDescription)")
        }
    }
    
    print("\n✨ Finished adding referral codes!")
    
    // Optionally list all codes
    do {
        let allCodes = try await admin.listAllCodes()
        print("\n📋 All referral codes:")
        for codeData in allCodes {
            let code = codeData["code"] as? String ?? "Unknown"
            let name = codeData["influencerName"] as? String ?? "Unknown"
            let count = codeData["usageCount"] as? Int ?? 0
            print("  - \(code): \(name) (used \(count) times)")
        }
    } catch {
        print("⚠️ Could not list codes: \(error.localizedDescription)")
    }
}

// MARK: - How to Run This
/*
 Option 1: Add to your app temporarily (one-time use)
 
 1. Add this file to your Xcode project
 2. In your app's initialization (e.g., FitHubApp.swift or AppContext.swift), 
    add a one-time call:
 
    Task {
        await addAllReferralCodes()
    }
 
 3. Run your app once
 4. Remove the call after codes are created
 5. Optionally delete this file or keep it for future use
 
 Option 2: Create a simple test target
 - Create a unit test or simple command-line tool
 - Call addAllReferralCodes() from there
 - Run once, then delete
 
 Option 3: Use in Xcode Playground
 - Create a new Playground
 - Copy necessary Firebase setup code
 - Run the function
*/

